{"attrMax":0,"name":"throw","nameSpace":"cf","attributes":{"errorcode":{"type":"string","description":"A custom error code that you supply.","required":false},"object":{"type":"any","description":"a native java exception Object, if this attribute is defined all other will be ignored","required":false},"type":{"type":"string","description":"A custom type or the predefined type Application. Do not enter any other predefined types because \n\t\tthey are not generated by ColdFusion applications. If you specify the exception type Application, you \n\t\tneed not specify a type for cfcatch, because the Application type is the default cfcatch type","required":false},"detail":{"type":"string","description":"A detailed description of the event. The ColdFusion server appends the position of the error to \n\t\tthis description; the server uses this parameter if an error is not caught by your code.","required":false},"message":{"type":"string","description":"A message that describes the exceptional event.","required":false},"extendedinfo":{"type":"string","description":"A custom error code that you supply.","required":false}},"bodyType":"prohibited","nameSpaceSeperator":"","hasNameAppendix":false,"attrMin":0,"description":"The cfthrow tag raises a developer-specified exception that can be caught with cfcatch tag \n  having any of the following type specifications - cfcatch type = 'custom_type', cfcatch type = 'Application'\n  'cfcatch' type = 'Any'","attributeType":"fix","parseBody":false}